[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "luggage"
version = "0.1.0"

dependencies = [
    "common",
    "pandas"
]

requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["."]